server:
    port: 10007
spring:
    cloud:
        stream:
            kafka:
                binder:
                auto-add-partitions: true
            bindings:
                news:
                    destinationi: "news"
                    content-type: "application/json"
                sms:
                    destinationi: "sms"
                    content-type: "application/json"
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
security:
    oauth2:
        resource:
            token-info-uri: "${auth-server}/oauth/check_token"
management:
  endpoints:
    web:
      exposure:
        include: "*"
