server:
    port: 10007
spring:
    kafka:
        producer:
            acks: 1
            retries: 5
            batch-size: 16384
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
security:
    oauth2:
        resource:
            token-info-uri: "${auth-server}/oauth/check_token"
management:
  endpoints:
    web:
      exposure:
        include: "*"
