server:
    port: 10007
spring:
    cloud:
        stream:
            kafka:
                binder:
                    auto-add-partitions: true
            bindings:
                news:
                    destinationi: "news"
                    content-type: "application/json"
                sms:
                    destinationi: "sms"
                    content-type: "application/json"
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
security:
    oauth2:
        client:
            access-token-uri: "${auth-server}/oauth/token"
            client-id: '{cipher}a760e23ee96fadcdb72e95f2f2edd1c2b86f51af2244d9679258ea77c5454667'
            client-secret: '{cipher}a1a933175d017dcf64df245ca86de11ed2ec1b34153044b08d2ea508c7c0264eafa73526184dee20218d6a3195729d23'
            scope: "account_info"
            user-authorization-uri: "${auth-server}/oauth/authorize"
        resource:
            token-info-uri: "${auth-server}/oauth/check_token"
management:
  endpoints:
    web:
      exposure:
        include: "*"
