logging:
  level:
    com.rcircle.service.auth.*: "DEBUG"
client:
    config:
        grant: "authorization_code;refresh_token"
        id: "{cipher}ced6fca023db53322bf69ba7b070f3e697f78c360fd6b1b4764cb4df3d19a71b"
        scopes: "account_info;"
        secret: "{cipher}9ffc306f5b8e9665bc3dd0f82acb7e2f2c5f7eb12c567c6cf335b263ca4a41595f07de47fa7f098946c2976faff4502f"
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
server:
    port: 10004
    servlet:
        session:
            cookie.name: "AUTHSESSION"
spring:
    redis:
        password: "{cipher}e864877a785f81037cc1eb7e65c9a920dfe0a6a45989795dd59a6330386420d45e16034436a7dee7bd01d1f155af2755"
        port: 6379
token:
    browse:
        access:
            validity: 259200
        refresh:
            validity: 604800
    upload:
        access:
            validity: 6400
        refresh:
            validity: 604800
tokenkey:
    jks:
        private:
            key: "{cipher}5dfc8ed6a27fc6d9d7ac9176afe853e6e9de9cd342262cb39603ee703ee8e4ff"

management:
   endpoints:
     web:
       exposure:
         include: "*"
