server:
  port: 10006
  servlet:
    session:
      cookie:
        name: "UISESSION"
spring:
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
  cloud:
    stream:
      bindings:
        hls:
          destination: "hls"
          content-type: "application/json"
          group: "hlsgroup"
        news:
          destination: "news"
          content-type: "application/json"
          group: "newsgroup"
        sms:
          destination: "sms"
          content-type: "application/json"
          group: "smsgroup"
  sleuth:
    sampler:
      probability: 1
ribbon:
  ConnectTimeout: 15000
  readTimeout: 30000
zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: "service-resource, service-auth, service-account"
  ignored-services: "*"
  service-resource:
    sensitive-headers:
  routes:
    service-resource:
      path: "/blog/api/**"
      strip-prefix: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
security:
  oauth2:
    client:
      client-id: "{cipher}7b04d124195414eabb2c0886575c0722c70217ab1878f274e1f6f58448afe022"
      client-secret: "{cipher}6546dadb476de5ea959716629e80a878f493bb71481c71a894a09712e4bf78b9bfdf6c89d6151ae5452bd412c8212993"
management:
   endpoints:
     web:
       exposure:
         include: "*"

