spring:
  cloud:
    stream:
      kafka:
        binder:
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
      hls:
        group: "stream"
server:
  address: "127.0.0.1"
  port: 10008
security:
  oauth2:
    resource:
      token-info-uri: "${auth-server}/oauth/check_token"
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
ffmpeg:
  path:
    linux: "/usr/local/bin/"
    windows: "E:\\Program Files\\ffmpeg-4.1.3-win64-static\\bin\\"
eureka-server: "localhost:10001"

