server:
  port: 10003
logging:
  level:
    com.ray.service.account.mapper: "debug"
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "{cipher}33b487778ccbf276d9428b36d6328515ec2af9e42e8c4c3cbf93c712e3acd8cbd310da1c70bef41e829bf1b508852f58"
    password: "{cipher}dd0e9b868ab50d3a4d8319b816834da448d92fe5c11d051a635fb22d8ee59be6"
  redis:
    host: "localhost"
    port: 6379
    password: "{cipher}4eea9dd2fb8e9f830e48a7dfe058b369c758d6d615046e3c83f0f96ace3a983852ed884782fe1604037d7ad30b7ae758"
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: "-1ms"
        min-idle: 0
eureka-server: "localhost:10001"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://${eureka-server}/eureka/"
auth-server: "http://localhost:10010"
security:
  oauth2:
    client:
      client-id: "{cipher}24446973440cf40c5fd4c7bc31c5148facd03fe34681d2337abfe3d1a8083e4e"
      client-secret: "{cipher}426cba3f6d6b4fe2ea89075ba7cab4227c82bfc664aec0f9461f945366f436ad097e4b954e79edcbfa7310e8f4730e4f"
      scope: "account_info"
      access-token-uri: "${auth-server}/oauth/token"
      user-authorization-uri: "${auth-server}/oauth/authorize"
    resource:
      token-info-uri: "${auth-server}/oauth/check_token" 
