server:
  address: "127.0.0.1"
  port: 10003
logging:
  level:
    com.ray.service.account.mapper: "debug"
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "{cipher}c7e362ea7542604de3c568b37152a7d48068fe87cf70804d37209c4e4479cea62f22022a8aed0df0aabfb15c44f489ed"
    password: "{cipher}25424ecc44352efa47b2cff8ad46845ce2518a289f9694059bb7f429d6b8cbe5"
  redis:
    host: "localhost"
    port: 6379
    password: "{cipher}51eb20c779501e2c5482a7764d37e6d65e2744237849dddc6192bf19bbbbf86573142b1307ecc5595e414b3c17a25ea0"
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: "-1ms"
        min-idle: 0
eureka-server: "localhost:10001"
eureka:
  instance:
    ip-address: "127.0.0.1"
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://${eureka-server}/eureka/"
auth-server: "http://localhost:10004"
security:
  oauth2:
    client:
      client-id: "{cipher}24446973440cf40c5fd4c7bc31c5148facd03fe34681d2337abfe3d1a8083e4e"
      client-secret: "{cipher}426cba3f6d6b4fe2ea89075ba7cab4227c82bfc664aec0f9461f945366f436ad097e4b954e79edcbfa7310e8f4730e4f"
      scope: "account_info"
      access-token-uri: "${auth-server}/oauth/token"
      user-authorization-uri: "${auth-server}/oauth/authorize"
    resource:
      token-info-uri: "${auth-server}/oauth/check_token" 
    jwt:
      publickey:
        local: "publickey.txt"
        remote: "${auth-server}/oauth/token_key"
