server:
  port: 10003
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "{cipher}33b487778ccbf276d9428b36d6328515ec2af9e42e8c4c3cbf93c712e3acd8cbd310da1c70bef41e829bf1b508852f58"
    password: "{cipher}dd0e9b868ab50d3a4d8319b816834da448d92fe5c11d051a635fb22d8ee59be6"
eureka-server=localhost: 10001
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://${eureka-server}/eureka/"
